document.writeln("<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">");
document.writeln("                    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"");
document.writeln("                        data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\"");
document.writeln("              a          aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
document.writeln("                        <span class=\"navbar-toggler-icon\"></span>");
document.writeln("                    </button>");
document.writeln("");
document.writeln("                    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
document.writeln("                        <ul class=\"navbar-nav mr-auto\">");
document.writeln("                            <li class=\'nav-item\'>");
document.writeln("                                <a class=\'nav-link\' href=\'index.html\'>Overview</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'nav-item\'>");
document.writeln("                                <a class=\'nav-link\' href=\'colours.html\'>Colours</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'nav-item\'>");
document.writeln("                                <a class=\'nav-link\' href=\'typography.html\'>Typography</a>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'nav-item dropdown\'>");
document.writeln("                                <a class=\'nav-link dropdown-toggle\' href=\'elements.html\' id=\'navbarDropdownMenuLink1\'");
document.writeln("                                    data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                                    Elements");
document.writeln("                                </a>");
document.writeln("                                <div class=\'dropdown-menu\' aria-labelledby=\'navbarDropdownMenuLink1\'>");
document.writeln("                                    <a class=\'dropdown-item\' href=\'elements.html#button\'>Button</a>");
document.writeln("                                    <a class=\'dropdown-item\' href=\'elements.html#input\'>Input</a>");
document.writeln("                                    <a class=\'dropdown-item\' href=\'elements.html#textarea\'>Textarea</a>");
document.writeln("                                    <a class=\'dropdown-item\' href=\'elements.html#checkbox\'>Checkbox</a>");
document.writeln("                                    <a class=\'dropdown-item\' href=\'elements.html#radiobox\'>Radiobox</a>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                            <li class=\'nav-item dropdown\'>");
document.writeln("                                <a class=\'nav-link dropdown-toggle\' href=\'components.html\' id=\'navbarDropdownMenuLink2\'");
document.writeln("                                    data-toggle=\'dropdown\' aria-haspopup=\'true\' aria-expanded=\'false\'>");
document.writeln("                                    Components");
document.writeln("                                </a>");
document.writeln("                                <div class=\'dropdown-menu\' aria-labelledby=\'navbarDropdownMenuLink2\'>");
document.writeln("                                    <a class=\'dropdown-item\' href=\'components.html#table\'>table</a>");
document.writeln("                                </div>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </nav>");