document.writeln("<nav class=\"navbar navbar-expand nav-main\">");
document.writeln("            <div class=\"collapse navbar-collapse\">");
document.writeln("                <ul class=\"navbar-nav mr-auto nav-main-ul\">");
document.writeln("                    <li class=\"nav-item nav-main-li active\">");
document.writeln("                        <a class=\"nav-link nav-main-link\" href=\"#\">總覽</a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"nav-item dropdown nav-main-li\" data-hover=\"dropdown\">");
document.writeln("                        <a class=\"nav-link nav-main-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink1\"");
document.writeln("                            role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"");
document.writeln("                            data-hover=\"dropdown\">");
document.writeln("                            辦公室裝潢/設備");
document.writeln("                        </a>");
document.writeln("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink1\">");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">冷氣</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">桌子</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">椅子</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">影印機</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">櫃子</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">燈管/燈泡</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">咖啡機</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">冰箱</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">碎紙機</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">門</a>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"nav-item dropdown nav-main-li\" data-hover=\"dropdown\">");
document.writeln("                        <a class=\"nav-link nav-main-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink2\"");
document.writeln("                            role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"");
document.writeln("                            data-hover=\"dropdown\">");
document.writeln("                            電腦/周邊");
document.writeln("                        </a>");
document.writeln("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink2\">");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">電腦</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">滑鼠</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">螢幕</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">硬碟</a>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"nav-item dropdown nav-main-li\" data-hover=\"dropdown\">");
document.writeln("                        <a class=\"nav-link nav-main-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink3\"");
document.writeln("                            role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"");
document.writeln("                            data-hover=\"dropdown\">");
document.writeln("                            3C產品/網路");
document.writeln("                        </a>");
document.writeln("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink3\">");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">電話</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">網路分享器</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">手機</a>");
document.writeln("                            <a class=\"dropdown-item\" href=\"#\">投影設備</a>");
document.writeln("                        </div>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"nav-item nav-main-li\">");
document.writeln("                        <a class=\"nav-link nav-main-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink4\"");
document.writeln("                            role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"");
document.writeln("                            data-hover=\"dropdown\">");
document.writeln("                            4");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"nav-item nav-main-li\">");
document.writeln("                        <a class=\"nav-link nav-main-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink5\"");
document.writeln("                            role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"");
document.writeln("                            data-hover=\"dropdown\">");
document.writeln("                            5");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\"nav-item nav-main-li\">");
document.writeln("                        <a class=\"nav-link nav-main-link dropdown-toggle\" href=\"#\" id=\"navbarDropdownMenuLink6\"");
document.writeln("                            role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\"");
document.writeln("                            data-hover=\"dropdown\">");
document.writeln("                            6");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </nav>");
document.writeln("");
document.writeln("        <div class=\"menu-mob collapse\" id=\"navbarSupportedContent\">");
document.writeln("            <div class=\"ctrlbar\">");
document.writeln("                <button class=\"close\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"");
document.writeln("                    aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
document.writeln("                    <div class=\"icons-nav-cancel\"></div>");
document.writeln("                </button>");
document.writeln("            </div>");
document.writeln("            <nav class=\"navbar\">");
document.writeln("                <div class=\"navbar-collapse\">");
document.writeln("                    <ul class=\"navbar-nav\">");
document.writeln("                        <li> <a class=\"nav-link\" href=\"#\">總覽</a></li>");
document.writeln("                        <li class=\"nav-item dropdown show\">");
document.writeln("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\"");
document.writeln("                                aria-expanded=\"true\" id=\"navbarDropdownMenuLink1\">");
document.writeln("                                辦公室裝潢/設備");
document.writeln("                                <i class=\"icons-ic-dropdown-down-white i-up\"></i>");
document.writeln("                                <i class=\"icons-ic-dropdown-down-white i-down\"></i>");
document.writeln("                            </a>");
document.writeln("                            <div class=\"dropdown-menu show\" aria-labelledby=\"navbarDropdownMenuLink1\"");
document.writeln("                                style=\"display: block;\">");
document.writeln("                                <ul class=\"navbar-nav\">");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">冷氣</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">桌子</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">椅子</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">影印機</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">櫃子</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">燈管/燈泡</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">咖啡機</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">冰箱</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">碎紙機</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">門</a>");
document.writeln("                                    </li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li class=\"nav-item dropdown\">");
document.writeln("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\"");
document.writeln("                                aria-expanded=\"false\" id=\"navbarDropdownMenuLink2\">");
document.writeln("                                電腦/周邊");
document.writeln("                                <i class=\"icons-ic-dropdown-down-white i-up\"></i>");
document.writeln("                                <i class=\"icons-ic-dropdown-down-white i-down\"></i>");
document.writeln("                            </a>");
document.writeln("                            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink2\">");
document.writeln("                                <ul class=\"navbar-nav\">");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">電腦</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">滑鼠</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">螢幕</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">硬碟</a>");
document.writeln("                                    </li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li class=\"nav-item dropdown\">");
document.writeln("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\" aria-haspopup=\"true\"");
document.writeln("                                aria-expanded=\"false\" id=\"navbarDropdownMenuLink2\">");
document.writeln("                                3C產品/網路");
document.writeln("                                <i class=\"icons-ic-dropdown-down-white i-up\"></i>");
document.writeln("                                <i class=\"icons-ic-dropdown-down-white i-down\"></i>");
document.writeln("                            </a>");
document.writeln("                            <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink2\">");
document.writeln("                                <ul class=\"navbar-nav\">");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">電話</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">網路分享器</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">手機</a>");
document.writeln("                                    </li>");
document.writeln("                                    <li class=\"nav-item\">");
document.writeln("                                        <a class=\"nav-link\" href=\"#\">投影設備</a>");
document.writeln("                                    </li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </nav>");
document.writeln("        </div>");